name: graphql_client_generator
description: The GraphQL client generator.
version: 0.0.0
homepage: https://github.com/hourliert/graphql_client/graphql_client_generator
author: Thomas Hourlier <hourliert@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  logging: ^0.11.3
  build: ^0.7.0
  build_barback: ^0.4.0
  code_builder: ^2.0.0-alpha+1
  dart_style: ^1.0.7
  graphql_parser: ^1.0.0

dev_dependencies:
  test: ^0.12.0
