name: graphql_client
description: A GraphQL client.
version: 0.0.4
homepage: https://github.com/hourliert/graphql_client
author: Thomas Hourlier <hourliert@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  http: ^0.11.3
  logging: ^0.11.3
  meta: ^1.1.1

dev_dependencies:
  test: ^0.12.0
